// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function OnExtractorFound(arg1:string):Promise<void>;

export function OnExtractorTypeFound(arg1:string,arg2:string):Promise<void>;

export function OnMediaQueried(arg1:number):Promise<void>;

export function OnQueryCompleted(arg1:number):Promise<void>;

export function QueryMedia(arg1:string,arg2:number):Promise<Array<model.Media>>;
