// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownloads() {
  return window['go']['main']['App']['CancelDownloads']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function IsOutdated() {
  return window['go']['main']['App']['IsOutdated']();
}

export function OnExtractorFound(arg1) {
  return window['go']['main']['App']['OnExtractorFound'](arg1);
}

export function OnExtractorTypeFound(arg1, arg2) {
  return window['go']['main']['App']['OnExtractorTypeFound'](arg1, arg2);
}

export function OnMediaDownloaded(arg1, arg2) {
  return window['go']['main']['App']['OnMediaDownloaded'](arg1, arg2);
}

export function OnMediaQueried(arg1) {
  return window['go']['main']['App']['OnMediaQueried'](arg1);
}

export function OnQueryCompleted(arg1, arg2) {
  return window['go']['main']['App']['OnQueryCompleted'](arg1, arg2);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function QueryMedia(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['QueryMedia'](arg1, arg2, arg3, arg4, arg5);
}

export function StartDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3);
}

export function StopQuery() {
  return window['go']['main']['App']['StopQuery']();
}
