// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnExtractorFound(arg1) {
  return window['go']['main']['App']['OnExtractorFound'](arg1);
}

export function OnExtractorTypeFound(arg1, arg2) {
  return window['go']['main']['App']['OnExtractorTypeFound'](arg1, arg2);
}

export function OnMediaQueried(arg1) {
  return window['go']['main']['App']['OnMediaQueried'](arg1);
}

export function OnQueryCompleted(arg1) {
  return window['go']['main']['App']['OnQueryCompleted'](arg1);
}

export function QueryMedia(arg1, arg2) {
  return window['go']['main']['App']['QueryMedia'](arg1, arg2);
}
