// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shared} from '../models';
import {model} from '../models';

export function GetHomeDirectory():Promise<string>;

export function OnExtractorFound(arg1:string):Promise<void>;

export function OnExtractorTypeFound(arg1:string,arg2:string):Promise<void>;

export function OnMediaDownloaded(arg1:shared.Download):Promise<void>;

export function OnMediaQueried(arg1:number):Promise<void>;

export function OnQueryCompleted(arg1:number):Promise<void>;

export function OpenDirectory(arg1:string):Promise<string>;

export function QueryMedia(arg1:string,arg2:number,arg3:boolean):Promise<Array<model.Media>>;

export function StartDownload(arg1:Array<model.Media>,arg2:string,arg3:number):Promise<Array<shared.Download>>;
